# Generated by Django 6.0.3 on 2026-03-29 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_job_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='Description',
            new_name='description',
        ),
        migrations.AddField(
            model_name='job',
            name='published_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
