# Generated by Django 6.0.3 on 2026-03-29 07:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_rename_description_job_description_job_published_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='published_at',
        ),
        migrations.AddField(
            model_name='job',
            name='published_a',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
