# Generated by Django 6.0.3 on 2026-03-29 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_remove_job_published_at_job_published_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='published_a',
        ),
    ]
